export const REPORT_TOTAL_REVENUE = 'REPORT_TOTAL_REVENUE'
export const REPORT_TOP_SELLERS = 'REPORT_TOP_SELLERS'
export const REPORT_GRAPH_DATA = 'REPORT_GRAPH_DATA'
export const REPORT_DOWNLOAD_REPORT = 'REPORT_DOWNLOAD_REPORT'