import {
    PRODUCT_SEARCH,
    PRODUCT_VENDORS,
    PRODUCT_DETAILS,
    PRODUCT_VENDOR_DETAILS,
    PRODUCT_FAVORITE,
    PRODUCT_MODIFY,
    PRODCUT_DELETE,
    PRODUCT_IMAGE_SAVE,
    PRODUCT_DELETE_IMAGE,
    PRODUCT_VIEW_FAVORITE,
    PRODUCT_MODIFY_REVIEWS,
    PRODUCT_LIST_REVIEW,
    PRODUCT_DELETE_REVIEW
} from '../actions/product'