import {
    USER_TRANSACTIONS,
    USER_PROFILE_UPDATE,
    USER_IMAGE_SAVE,
    USER_DISPLAY_DELIVERY_ADDRESS,
    USER_DELIVERY_ADDRESS,
    USER_DELIVERY_ADDRESS_DELETE,
    USER_COMPLETED_ORDER,
    USER_DELETE_ACCOUNT
} from '../actions/user'