import {
    VENDOR_VIEW_PRODUCTS,
    VENDOR_VIEW_PROFILE,
    VENDOR_CONRIM_CASH_PAY,
    VENDOR_VIEW_COMPANY_ADDRESS,
    VENDOR_COMPANY_ADDRESS,
    VENDOR_DELETE_COMPANY_ADDRESS,
    VENDOR_SHOW_REQUEST,
    VENDOR_REQUEST_DETAIL,
    VENDOR_ACCEPT_OR_REJECT_REQUEST,
    VENDOR_PROCESS_REQUEST_STATUS,
    VENDOR_OPERATION_DAY,
    VENDOR_VIEW_OPERATION_DAYS
} from '../actions/vendor'